"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob

APP = ['pronterface.py']
DATA_FILES = [
	('',['P-face.ico','plater.ico','pronsole.ico']),
	('images',glob('images/*.png'))
]
OPTIONS = {'arch': 'i386', 'argv_emulation': True, 'includes': 'wx','iconfile':'P-face.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
